### ISSUE TITLE
Fixed bootstrap.php and still not getting generated pdf

### ISSUE THREAD

**Issue by iliasiovis** [fdeschenes/cakephp-dompdf-view#1]
Hello,
looks like a great plugin but I just cannot make it work "out of the box".

This is what I get at first glance:
Fatal error: Uncaught exception 'ConfigureException' with message 'Could not load configuration files: .../app/Plugin/cakephp-dompdf-view/Config/Dompdf.php

which goes away if I change the following line of the bootstrap.php inside the Config folder of the plugin
Configure::load('cakephp-dompdf-view.Dompdf');
to
Configure::load('cakephp-dompdf-view.dompdf');

But then, when trying to generate a pdf all I get is an error message "File does not begin with %PDF" etc.
I checked the generated.pdf and it just contains the expected html (no specific pdf header info etc).

I have followed the instructions extensively and I've been banging my head on the wall 2 days now, any help would be really appreciated!

(CakePHP 2.0.5 and tried it with dompdf 0.6.0 beta3 and beta 2)

**Comment by niq000** [comment]
I made the same correction to the bootstrap file but am also getting the "file does not begin with %PDF" error message. I've tried dompdf 6.0alpha_1 through 6.0beta_3 without any success

**Comment by kikegarcia** [comment]
Same problem here...

**Comment by deldan** [comment]
Hi!

my problem is "DOMPDF_TEMP_DIR" is not writable, but the folder permissions is correct (777).

**Comment by fdeschenes** [comment]
Sorry for the delay in answering this. For some reason, I didn't get an email notification from GitHub that this ticket had been opened.

@iliasiovis: Your problem must be that you had renamed the folder to something else.  The plugin references itself and must be named as stated in the documentation or it'll give you that error. I just committed a new version which solved a few issues and I've decided to make the name friendlier (`Dompdf`). Make sure that the folder under plugin is named `Dompdf` (or `cakephp-dompdf-view` if you're using the older version).

@niq000 & @kikegarcia: If you haven't resolved your issue, could you please download the resulting PDF and open the file with a text editor.  They may be some debug information at the top that's preventing the PDF from outputting properly.  If so, please fix the errors and that should solve your problem.  Otherwise, let me know and I'll see what I can do.

@deldan: If you're talking about the warning at the top of your PDFs, that's not `DOMPDF_TEMP_DIR` but the rather the `APP/tmp/cache/dompdf` folder.
